version: "3.8"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"          
      - "443:443"        
      - "443:443/udp"    
    volumes:
      - ./caddy:/etc/caddy       
      - caddy_data:/data         
      - caddy_config:/config     
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
